In [4]:
# 플레이스 홀더와 변수의 개념 익히기
import tensorflow as tf

# tf.placeholder: 계산을 실행할 때 입력값을 받는 변수로 사용한다.
# None 은 크기가 정해지지 않았음을 의미한다.
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder_2:0", shape=(?, 3), dtype=float32)


In [8]:
# X placeholder에 넣을 값
# Placeholder에서 설정한 것 처럼, 두 번째 차원의 요소의 개수는 3개
x_data = [[1,2,3],[4,5,6]]

# tf.Variable: 그래프를 계산하면서 최적화 할 변수들. 이 값이 바로 신경망을 좌우하는 값.
# tf.random_normal: 각 변수들의 초기값을 정규분포 랜덤 값으로 초기화한다.
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

# 입력값과 변수들을 계산할 수식을 작성
# tf.matmul 처럼 mat* 로 되어 있는 함수로 행렬 계산을 수행
expr = tf.matmul(X,W) + b

sess = tf.Session()

sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
# expr 수식에는 X 라는 입력값이 필요합니다.
# 따라서 expr 실행시에는 이 변수에 대한 실제 입력값을 다음처럼 넣어줘야합니다.
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()


=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 1.52925634  0.42987505]
 [-0.68468034 -1.60710812]
 [-0.97272873  0.15991895]]
=== b ===
[[ 0.73328424]
 [ 0.61449349]]
=== expr ===
[[-2.02500629 -1.57130003]
 [-2.52825546 -4.74203348]]
